#!/bin/bash

CHOSTS=(
    'identity.comprobo.net'
    'workflow.comprobo.net'
    'media.comprobo.net'
)

USER=ubuntu
LOGDIR=/var/comprobo/log
LOCALDIR="/media/peter/Pete's Backup Dr/comprobo-logs"

for i in ${CHOSTS[@]}; do
    mkdir -p "$LOCALDIR/$i"
    rsync -Pchvaz -e "ssh -i $HOME/.ssh/comprobo-dev.pem" "$USER@$i:$LOGDIR/*" "$LOCALDIR/$i/"
done

exit 0
