#!/usr/bin/env ruby
require 'json'

now = ARGV[0]
later = ARGV[1]

sample_size ||= 25
interval    ||= 3600

now ||= Time.now.getutc.to_i
later ||= now + interval

puts (now...later).to_a.sample(sample_size).sort {|a, b| a <=> b}.reverse
